# NumPy exercises

Some  of these come from / are inspired from https://github.com/rougier/numpy-100 and http://www.scipy-lectures.org/intro/numpy/exercises.html

You might want to look over these lists as well.

In [1]:
import numpy as np

## Q1

We can use `np.random.random_sample()` to create an array with random values.  By default, these will be in the range `[0.0, 1.0)`.  You can
multiple the output and add a scalar to it to get it to be in a different range.

Create a 10 x 10 array initialized with random numbers that lie between 0 and 10.

Then compute the average of the array (there is a numpy function for this, `np.mean()`).

In [2]:
# allocate a random 10 by 10 array and scale by 10.
a = np.random.random_sample((10,10))*10.

In [3]:
a.mean()

4.6992729069403305

In [4]:
# seems reasonably close to 5.0

## Q2

Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.

In [5]:
np.arange(1, 16).reshape((3, 5)).T

np.arange(1, 16).reshape((5, 3), order='F')

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

## Q3

Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [6]:
a = np.ones((4, 5), dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
a[1:-1, 1:-1] = 0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [8]:
c = np.arange(1, 21).reshape(4, 5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
c[:-1] = 2*c[:-1]
c

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [16, 17, 18, 19, 20]])

In [10]:
c[1:-1, 1:-1]  = 0
c

array([[ 2,  4,  6,  8, 10],
       [12,  0,  0,  0, 20],
       [22,  0,  0,  0, 30],
       [16, 17, 18, 19, 20]])

## Q4

  * Create an array with angles in degrees 0, 15, 30, ... 90 (i.e., every 15 degrees up to 90).

  * Now create 3 new arrays with the sine, cosine, and tangent of the elements of the first array
  
  * Finally, calculate the inverse sine, inverse cosine, and inverse tangent the arrays above and compare to the original angles

In [11]:
x = np.arange(0, 90., 15.) #  [deg]

sinx = np.sin(np.deg2rad(x))
cosx = np.cos(np.deg2rad(x))
tanx = np.tan(np.deg2rad(x))

inv_sinx = np.rad2deg(np.arcsin(sinx))
inv_cosx = np.rad2deg(np.arccos(cosx))
inv_tanx = np.rad2deg(np.arctan(tanx))

np.allclose(x, inv_sinx), np.allclose(x, inv_cosx), np.allclose(x, inv_tanx)

(True, True, True)

## Q5

Given the array:
```
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
```
calculate the difference of each element with its neighbor.

In [12]:
x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])

x[1:] - x[:-1]  # or np.diff(x)

array([-2,  3,  3,  3, -4,  6,  2, -9])

## Q6

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook (you can download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [13]:
data = np.loadtxt('sample.txt')
bin_counts, bin_edges = np.histogram(data)

In [16]:
# using a loop to step-by-step calculation of bin center
for (c, b_l, b_r) in zip(bin_counts, bin_edges[:-1], bin_edges[1:]):
    print("{}: {}".format((b_l + b_r)/2, c))

-24.109006493430737: 6
-11.150163704648554: 23
1.8086790841336278: 52
14.767521872915811: 37
27.726364661697996: 16
40.68520745048018: 14
53.64405023926236: 13
66.60289302804455: 13
79.56173581682673: 13
92.5205786056089: 13


In [17]:
# using numpy to calculate centers and then loop
bin_centers = 0.5*(bin_edges[:-1] + bin_edges[1:])

for c, b_c in zip(bin_counts, bin_centers):
    print("{}: {}".format(b_c, c))

-24.109006493430737: 6
-11.150163704648554: 23
1.8086790841336278: 52
14.767521872915811: 37
27.726364661697996: 16
40.68520745048018: 14
53.64405023926236: 13
66.60289302804455: 13
79.56173581682673: 13
92.5205786056089: 13


## Q7

NumPy has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`

In [18]:
a = np.random.random((100,))

a_mean = a.sum()/len(a)
a_squares_sum = np.sum((a - a_mean)**2.)
a_mean_squares_sum = a_squares_sum/len(a)
a_std = np.sqrt(a_mean_squares_sum)

print(a_std, np.std(a))

0.288875666093 0.288875666093
